//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PausMenu.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PausMenu : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PausMenu()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PausMenu"",
    ""maps"": [
        {
            ""name"": ""Menu"",
            ""id"": ""a1425c05-33fd-49ce-811e-e9134c4fe6ba"",
            ""actions"": [
                {
                    ""name"": ""MenuPressed"",
                    ""type"": ""Button"",
                    ""id"": ""b6882bc2-54aa-4983-a81f-d1c468ee9720"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d0c52ca9-f457-452b-9b8e-13ddd039d119"",
                    ""path"": ""<XRController>{LeftHand}/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuPressed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_MenuPressed = m_Menu.FindAction("MenuPressed", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Menu
    private readonly InputActionMap m_Menu;
    private IMenuActions m_MenuActionsCallbackInterface;
    private readonly InputAction m_Menu_MenuPressed;
    public struct MenuActions
    {
        private @PausMenu m_Wrapper;
        public MenuActions(@PausMenu wrapper) { m_Wrapper = wrapper; }
        public InputAction @MenuPressed => m_Wrapper.m_Menu_MenuPressed;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void SetCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterface != null)
            {
                @MenuPressed.started -= m_Wrapper.m_MenuActionsCallbackInterface.OnMenuPressed;
                @MenuPressed.performed -= m_Wrapper.m_MenuActionsCallbackInterface.OnMenuPressed;
                @MenuPressed.canceled -= m_Wrapper.m_MenuActionsCallbackInterface.OnMenuPressed;
            }
            m_Wrapper.m_MenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MenuPressed.started += instance.OnMenuPressed;
                @MenuPressed.performed += instance.OnMenuPressed;
                @MenuPressed.canceled += instance.OnMenuPressed;
            }
        }
    }
    public MenuActions @Menu => new MenuActions(this);
    public interface IMenuActions
    {
        void OnMenuPressed(InputAction.CallbackContext context);
    }
}
